/*
 * This file is generated by jOOQ.
*/
package com.nuxsoftware.kotlindemo.db.tables;


import com.nuxsoftware.kotlindemo.db.Indexes;
import com.nuxsoftware.kotlindemo.db.Keys;
import com.nuxsoftware.kotlindemo.db.Public;
import com.nuxsoftware.kotlindemo.db.tables.records.HrUserRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HrUser extends TableImpl<HrUserRecord> {

    private static final long serialVersionUID = 727341757;

    /**
     * The reference instance of <code>PUBLIC.HR_USER</code>
     */
    public static final HrUser HR_USER = new HrUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HrUserRecord> getRecordType() {
        return HrUserRecord.class;
    }

    /**
     * The column <code>PUBLIC.HR_USER.ID</code>.
     */
    public final TableField<HrUserRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.LOGIN</code>.
     */
    public final TableField<HrUserRecord, String> LOGIN = createField("LOGIN", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.PASSWORD_HASH</code>.
     */
    public final TableField<HrUserRecord, String> PASSWORD_HASH = createField("PASSWORD_HASH", org.jooq.impl.SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.FIRST_NAME</code>.
     */
    public final TableField<HrUserRecord, String> FIRST_NAME = createField("FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.LAST_NAME</code>.
     */
    public final TableField<HrUserRecord, String> LAST_NAME = createField("LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.EMAIL</code>.
     */
    public final TableField<HrUserRecord, String> EMAIL = createField("EMAIL", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.IMAGE_URL</code>.
     */
    public final TableField<HrUserRecord, String> IMAGE_URL = createField("IMAGE_URL", org.jooq.impl.SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.ACTIVATED</code>.
     */
    public final TableField<HrUserRecord, Boolean> ACTIVATED = createField("ACTIVATED", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.LANG_KEY</code>.
     */
    public final TableField<HrUserRecord, String> LANG_KEY = createField("LANG_KEY", org.jooq.impl.SQLDataType.VARCHAR(6), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.ACTIVATION_KEY</code>.
     */
    public final TableField<HrUserRecord, String> ACTIVATION_KEY = createField("ACTIVATION_KEY", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.RESET_KEY</code>.
     */
    public final TableField<HrUserRecord, String> RESET_KEY = createField("RESET_KEY", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.CREATED_BY</code>.
     */
    public final TableField<HrUserRecord, String> CREATED_BY = createField("CREATED_BY", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.CREATED_DATE</code>.
     */
    public final TableField<HrUserRecord, Timestamp> CREATED_DATE = createField("CREATED_DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.RESET_DATE</code>.
     */
    public final TableField<HrUserRecord, Timestamp> RESET_DATE = createField("RESET_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.HR_USER.LAST_MODIFIED_BY</code>.
     */
    public final TableField<HrUserRecord, String> LAST_MODIFIED_BY = createField("LAST_MODIFIED_BY", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>PUBLIC.HR_USER.LAST_MODIFIED_DATE</code>.
     */
    public final TableField<HrUserRecord, Timestamp> LAST_MODIFIED_DATE = createField("LAST_MODIFIED_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>PUBLIC.HR_USER</code> table reference
     */
    public HrUser() {
        this(DSL.name("HR_USER"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.HR_USER</code> table reference
     */
    public HrUser(String alias) {
        this(DSL.name(alias), HR_USER);
    }

    /**
     * Create an aliased <code>PUBLIC.HR_USER</code> table reference
     */
    public HrUser(Name alias) {
        this(alias, HR_USER);
    }

    private HrUser(Name alias, Table<HrUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private HrUser(Name alias, Table<HrUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IDX_HR_USER_EMAIL, Indexes.IDX_HR_USER_LOGIN, Indexes.PRIMARY_KEY_7, Indexes.UX_USER_EMAIL_INDEX_7, Indexes.UX_USER_LOGIN_INDEX_7);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<HrUserRecord> getPrimaryKey() {
        return Keys.PK_HR_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<HrUserRecord>> getKeys() {
        return Arrays.<UniqueKey<HrUserRecord>>asList(Keys.PK_HR_USER, Keys.UX_USER_LOGIN, Keys.UX_USER_EMAIL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrUser as(String alias) {
        return new HrUser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrUser as(Name alias) {
        return new HrUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HrUser rename(String name) {
        return new HrUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HrUser rename(Name name) {
        return new HrUser(name, null);
    }
}
