/*
 * This file is generated by jOOQ.
*/
package com.nuxsoftware.kotlindemo.db.tables.daos;


import com.nuxsoftware.kotlindemo.db.tables.Authority;
import com.nuxsoftware.kotlindemo.db.tables.records.AuthorityRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorityDao extends DAOImpl<AuthorityRecord, com.nuxsoftware.kotlindemo.db.tables.pojos.Authority, String> {

    /**
     * Create a new AuthorityDao without any configuration
     */
    public AuthorityDao() {
        super(Authority.AUTHORITY, com.nuxsoftware.kotlindemo.db.tables.pojos.Authority.class);
    }

    /**
     * Create a new AuthorityDao with an attached configuration
     */
    public AuthorityDao(Configuration configuration) {
        super(Authority.AUTHORITY, com.nuxsoftware.kotlindemo.db.tables.pojos.Authority.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.nuxsoftware.kotlindemo.db.tables.pojos.Authority object) {
        return object.getName();
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.nuxsoftware.kotlindemo.db.tables.pojos.Authority> fetchByName(String... values) {
        return fetch(Authority.AUTHORITY.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>NAME = value</code>
     */
    public com.nuxsoftware.kotlindemo.db.tables.pojos.Authority fetchOneByName(String value) {
        return fetchOne(Authority.AUTHORITY.NAME, value);
    }
}
