/*
 * This file is generated by jOOQ.
*/
package com.nuxsoftware.kotlindemo.db;


import com.nuxsoftware.kotlindemo.db.tables.Authority;
import com.nuxsoftware.kotlindemo.db.tables.Databasechangeloglock;
import com.nuxsoftware.kotlindemo.db.tables.HrUser;
import com.nuxsoftware.kotlindemo.db.tables.HrUserAuthority;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_F = Indexes0.PRIMARY_KEY_F;
    public static final Index PRIMARY_KEY_D = Indexes0.PRIMARY_KEY_D;
    public static final Index IDX_HR_USER_EMAIL = Indexes0.IDX_HR_USER_EMAIL;
    public static final Index IDX_HR_USER_LOGIN = Indexes0.IDX_HR_USER_LOGIN;
    public static final Index PRIMARY_KEY_7 = Indexes0.PRIMARY_KEY_7;
    public static final Index UX_USER_EMAIL_INDEX_7 = Indexes0.UX_USER_EMAIL_INDEX_7;
    public static final Index UX_USER_LOGIN_INDEX_7 = Indexes0.UX_USER_LOGIN_INDEX_7;
    public static final Index FK_AUTHORITY_NAME_INDEX_5 = Indexes0.FK_AUTHORITY_NAME_INDEX_5;
    public static final Index FK_USER_ID_INDEX_5 = Indexes0.FK_USER_ID_INDEX_5;
    public static final Index PRIMARY_KEY_5 = Indexes0.PRIMARY_KEY_5;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index PRIMARY_KEY_F = createIndex("PRIMARY_KEY_F", Authority.AUTHORITY, new OrderField[] { Authority.AUTHORITY.NAME }, true);
        public static Index PRIMARY_KEY_D = createIndex("PRIMARY_KEY_D", Databasechangeloglock.DATABASECHANGELOGLOCK, new OrderField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
        public static Index IDX_HR_USER_EMAIL = createIndex("IDX_HR_USER_EMAIL", HrUser.HR_USER, new OrderField[] { HrUser.HR_USER.EMAIL }, true);
        public static Index IDX_HR_USER_LOGIN = createIndex("IDX_HR_USER_LOGIN", HrUser.HR_USER, new OrderField[] { HrUser.HR_USER.LOGIN }, true);
        public static Index PRIMARY_KEY_7 = createIndex("PRIMARY_KEY_7", HrUser.HR_USER, new OrderField[] { HrUser.HR_USER.ID }, true);
        public static Index UX_USER_EMAIL_INDEX_7 = createIndex("UX_USER_EMAIL_INDEX_7", HrUser.HR_USER, new OrderField[] { HrUser.HR_USER.EMAIL }, true);
        public static Index UX_USER_LOGIN_INDEX_7 = createIndex("UX_USER_LOGIN_INDEX_7", HrUser.HR_USER, new OrderField[] { HrUser.HR_USER.LOGIN }, true);
        public static Index FK_AUTHORITY_NAME_INDEX_5 = createIndex("FK_AUTHORITY_NAME_INDEX_5", HrUserAuthority.HR_USER_AUTHORITY, new OrderField[] { HrUserAuthority.HR_USER_AUTHORITY.AUTHORITY_NAME }, false);
        public static Index FK_USER_ID_INDEX_5 = createIndex("FK_USER_ID_INDEX_5", HrUserAuthority.HR_USER_AUTHORITY, new OrderField[] { HrUserAuthority.HR_USER_AUTHORITY.HR_USER_ID }, false);
        public static Index PRIMARY_KEY_5 = createIndex("PRIMARY_KEY_5", HrUserAuthority.HR_USER_AUTHORITY, new OrderField[] { HrUserAuthority.HR_USER_AUTHORITY.HR_USER_ID, HrUserAuthority.HR_USER_AUTHORITY.AUTHORITY_NAME }, true);
    }
}
