/*
 * This file is generated by jOOQ.
*/
package com.nuxsoftware.kotlindemo.db;


import com.nuxsoftware.kotlindemo.db.tables.Authority;
import com.nuxsoftware.kotlindemo.db.tables.Databasechangelog;
import com.nuxsoftware.kotlindemo.db.tables.Databasechangeloglock;
import com.nuxsoftware.kotlindemo.db.tables.HrUser;
import com.nuxsoftware.kotlindemo.db.tables.HrUserAuthority;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 631330233;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.AUTHORITY</code>.
     */
    public final Authority AUTHORITY = com.nuxsoftware.kotlindemo.db.tables.Authority.AUTHORITY;

    /**
     * The table <code>PUBLIC.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = com.nuxsoftware.kotlindemo.db.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>PUBLIC.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = com.nuxsoftware.kotlindemo.db.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>PUBLIC.HR_USER</code>.
     */
    public final HrUser HR_USER = com.nuxsoftware.kotlindemo.db.tables.HrUser.HR_USER;

    /**
     * The table <code>PUBLIC.HR_USER_AUTHORITY</code>.
     */
    public final HrUserAuthority HR_USER_AUTHORITY = com.nuxsoftware.kotlindemo.db.tables.HrUserAuthority.HR_USER_AUTHORITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Authority.AUTHORITY,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            HrUser.HR_USER,
            HrUserAuthority.HR_USER_AUTHORITY);
    }
}
