/*
 * This file is generated by jOOQ.
*/
package com.nuxsoftware.kotlindemo.db;


import com.nuxsoftware.kotlindemo.db.tables.Authority;
import com.nuxsoftware.kotlindemo.db.tables.Databasechangelog;
import com.nuxsoftware.kotlindemo.db.tables.Databasechangeloglock;
import com.nuxsoftware.kotlindemo.db.tables.HrUser;
import com.nuxsoftware.kotlindemo.db.tables.HrUserAuthority;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUTHORITY</code>.
     */
    public static final Authority AUTHORITY = com.nuxsoftware.kotlindemo.db.tables.Authority.AUTHORITY;

    /**
     * The table <code>PUBLIC.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = com.nuxsoftware.kotlindemo.db.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>PUBLIC.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = com.nuxsoftware.kotlindemo.db.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>PUBLIC.HR_USER</code>.
     */
    public static final HrUser HR_USER = com.nuxsoftware.kotlindemo.db.tables.HrUser.HR_USER;

    /**
     * The table <code>PUBLIC.HR_USER_AUTHORITY</code>.
     */
    public static final HrUserAuthority HR_USER_AUTHORITY = com.nuxsoftware.kotlindemo.db.tables.HrUserAuthority.HR_USER_AUTHORITY;
}
